[2025-06-09T08:18:47.439+0000] {processor.py:157} INFO - Started process (PID=42) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:18:47.440+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:18:47.441+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:18:47.441+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:18:47.456+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:18:47.454+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:18:47.456+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:18:47.473+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.038 seconds
[2025-06-09T08:19:17.680+0000] {processor.py:157} INFO - Started process (PID=43) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:19:17.682+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:19:17.684+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:19:17.683+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:19:17.705+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:19:17.703+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:19:17.705+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:19:17.728+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.058 seconds
[2025-06-09T08:19:47.911+0000] {processor.py:157} INFO - Started process (PID=44) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:19:47.912+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:19:47.913+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:19:47.913+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:19:47.928+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:19:47.926+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:19:47.929+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:19:47.947+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.040 seconds
[2025-06-09T08:20:18.207+0000] {processor.py:157} INFO - Started process (PID=45) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:20:18.208+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:20:18.209+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:20:18.209+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:20:18.243+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:20:18.241+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:20:18.243+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:20:18.266+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.064 seconds
[2025-06-09T08:20:48.649+0000] {processor.py:157} INFO - Started process (PID=46) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:20:48.651+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:20:48.658+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:20:48.656+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:30:02.926+0000] {processor.py:157} INFO - Started process (PID=35) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:30:02.927+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:30:02.928+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:30:02.928+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:30:02.937+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:30:02.935+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:30:02.937+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:30:02.951+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.027 seconds
[2025-06-09T08:30:33.227+0000] {processor.py:157} INFO - Started process (PID=36) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:30:33.228+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:30:33.230+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:30:33.229+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:30:33.246+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:30:33.244+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:30:33.247+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:30:33.269+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.049 seconds
[2025-06-09T08:31:03.543+0000] {processor.py:157} INFO - Started process (PID=37) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:31:03.546+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:31:03.547+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:31:03.547+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:31:03.572+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:31:03.568+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:31:03.573+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:31:03.595+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.057 seconds
[2025-06-09T08:31:33.876+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:31:33.877+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:31:33.878+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:31:33.877+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:31:33.889+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:31:33.888+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:31:33.890+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:31:33.906+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.035 seconds
[2025-06-09T08:32:04.202+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:32:04.204+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:32:04.205+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:32:04.204+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:32:04.223+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:32:04.221+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:32:04.223+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:32:04.243+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.047 seconds
[2025-06-09T08:32:34.494+0000] {processor.py:157} INFO - Started process (PID=40) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:32:34.495+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:32:34.496+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:32:34.496+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:32:34.511+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:32:34.509+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:32:34.511+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:32:34.530+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.042 seconds
[2025-06-09T08:33:04.774+0000] {processor.py:157} INFO - Started process (PID=41) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:33:04.776+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:33:04.777+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:33:04.777+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:33:04.795+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:33:04.793+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:33:04.795+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:33:04.866+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.098 seconds
[2025-06-09T08:33:34.955+0000] {processor.py:157} INFO - Started process (PID=42) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:33:34.957+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:33:34.958+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:33:34.958+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:33:34.968+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:33:34.967+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:33:34.968+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:33:34.982+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.031 seconds
[2025-06-09T08:34:05.184+0000] {processor.py:157} INFO - Started process (PID=43) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:34:05.185+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:34:05.186+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:34:05.185+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:34:05.199+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:34:05.197+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:34:05.200+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:34:05.218+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.037 seconds
[2025-06-09T08:34:35.494+0000] {processor.py:157} INFO - Started process (PID=44) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:34:35.495+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:34:35.497+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:34:35.496+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:34:35.516+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:34:35.515+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:34:35.517+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:34:35.533+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.047 seconds
[2025-06-09T08:35:05.784+0000] {processor.py:157} INFO - Started process (PID=45) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:35:05.786+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:35:05.788+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:35:05.788+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:35:05.802+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:35:05.801+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:35:05.803+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:35:05.831+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.051 seconds
[2025-06-09T08:35:36.075+0000] {processor.py:157} INFO - Started process (PID=46) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:35:36.077+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:35:36.079+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:35:36.078+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:35:36.125+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:35:36.121+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:35:36.125+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:35:36.146+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.078 seconds
[2025-06-09T08:36:06.418+0000] {processor.py:157} INFO - Started process (PID=47) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:36:06.420+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:36:06.422+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:36:06.421+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:36:06.441+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:36:06.439+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:36:06.441+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:36:06.475+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.062 seconds
[2025-06-09T08:36:36.779+0000] {processor.py:157} INFO - Started process (PID=48) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:36:36.781+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:36:36.784+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:36:36.782+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:36:36.810+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:36:36.808+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:36:36.811+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:36:36.832+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.068 seconds
[2025-06-09T08:37:07.155+0000] {processor.py:157} INFO - Started process (PID=49) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:37:07.158+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:37:07.166+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:37:07.161+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:37:07.184+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:37:07.182+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:37:07.184+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:37:07.202+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.055 seconds
[2025-06-09T08:37:37.366+0000] {processor.py:157} INFO - Started process (PID=50) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:37:37.367+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:37:37.368+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:37:37.368+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:37:37.379+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:37:37.378+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:37:37.380+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:37:37.479+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.115 seconds
[2025-06-09T08:38:07.582+0000] {processor.py:157} INFO - Started process (PID=51) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:38:07.583+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:38:07.585+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:38:07.584+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:38:07.605+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:38:07.604+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:38:07.605+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:38:07.625+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.056 seconds
[2025-06-09T08:38:37.940+0000] {processor.py:157} INFO - Started process (PID=52) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:38:37.953+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:38:37.955+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:38:37.955+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:38:37.978+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:38:37.976+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:38:37.979+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:38:38.004+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.090 seconds
[2025-06-09T08:39:08.243+0000] {processor.py:157} INFO - Started process (PID=53) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:39:08.245+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:39:08.247+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:39:08.246+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:39:08.271+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:39:08.267+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:39:08.271+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:39:08.302+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.067 seconds
[2025-06-09T08:39:38.684+0000] {processor.py:157} INFO - Started process (PID=54) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:39:38.687+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:39:38.688+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:39:38.688+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:39:38.708+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:39:38.706+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:39:38.708+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:39:38.729+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.067 seconds
[2025-06-09T08:40:09.063+0000] {processor.py:157} INFO - Started process (PID=55) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:40:09.065+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:40:09.066+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:40:09.066+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:40:09.085+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:40:09.084+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/online_retail_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/online_retail_etl.py", line 51, in <module>
    transform_task = DummyOperator(task_id='transform_placeholder', dag=dag)
NameError: name 'DummyOperator' is not defined
[2025-06-09T08:40:09.086+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:40:09.106+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.059 seconds
[2025-06-09T08:40:30.292+0000] {processor.py:157} INFO - Started process (PID=56) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:40:30.294+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:40:30.298+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:40:30.296+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:40:30.337+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:40:30.335+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:40:30.353+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:40:30.507+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:40:30.506+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:online_retail_etl
[2025-06-09T08:40:30.515+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:40:30.515+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:online_retail_etl
[2025-06-09T08:40:30.518+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:40:30.518+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:online_retail_etl
[2025-06-09T08:40:30.527+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:40:30.527+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:40:30.535+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:40:30.534+0000] {dag.py:2763} INFO - Creating ORM DAG for online_retail_etl
[2025-06-09T08:40:30.546+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:40:30.546+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:40:30.560+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.275 seconds
[2025-06-09T08:41:00.838+0000] {processor.py:157} INFO - Started process (PID=57) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:41:00.841+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:41:00.843+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:41:00.842+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:41:00.867+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:41:00.866+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:41:00.871+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:41:00.916+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:41:00.916+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:41:00.934+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:41:00.934+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:41:00.946+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.116 seconds
[2025-06-09T08:41:31.181+0000] {processor.py:157} INFO - Started process (PID=58) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:41:31.183+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:41:31.185+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:41:31.185+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:41:31.238+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:41:31.236+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:41:31.242+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:41:31.270+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:41:31.270+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:41:31.296+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:41:31.295+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:41:31.308+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.137 seconds
[2025-06-09T08:42:01.524+0000] {processor.py:157} INFO - Started process (PID=59) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:42:01.525+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:42:01.526+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:42:01.526+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:42:01.551+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:42:01.550+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:42:01.555+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:42:01.588+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:42:01.587+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:42:01.622+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:42:01.622+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:42:01.635+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.117 seconds
[2025-06-09T08:42:31.897+0000] {processor.py:157} INFO - Started process (PID=60) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:42:31.899+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:42:31.900+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:42:31.900+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:42:31.952+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:42:31.950+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:42:31.956+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:42:31.985+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:42:31.985+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:42:32.002+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:42:32.001+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:42:32.012+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.124 seconds
[2025-06-09T08:43:02.203+0000] {processor.py:157} INFO - Started process (PID=61) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:43:02.206+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:43:02.208+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:43:02.207+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:43:02.236+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:43:02.235+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:43:02.241+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:43:02.272+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:43:02.272+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:43:02.298+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:43:02.298+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:43:02.309+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.114 seconds
[2025-06-09T08:43:32.623+0000] {processor.py:157} INFO - Started process (PID=62) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:43:32.626+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:43:32.628+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:43:32.627+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:43:32.656+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:43:32.655+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:43:32.667+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:43:32.709+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:43:32.709+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:43:32.726+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:43:32.726+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:43:32.738+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.121 seconds
[2025-06-09T08:44:03.020+0000] {processor.py:157} INFO - Started process (PID=63) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:44:03.023+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:44:03.024+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:44:03.024+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:44:03.052+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:44:03.051+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:44:03.057+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:44:03.086+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:44:03.086+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:44:03.108+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:44:03.107+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:44:03.121+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.108 seconds
[2025-06-09T08:44:33.392+0000] {processor.py:157} INFO - Started process (PID=64) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:44:33.394+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:44:33.396+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:44:33.395+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:44:33.434+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:44:33.433+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:44:33.439+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:44:33.469+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:44:33.469+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:44:33.488+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:44:33.488+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:44:33.509+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.123 seconds
[2025-06-09T08:45:03.748+0000] {processor.py:157} INFO - Started process (PID=65) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:45:03.749+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:45:03.750+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:45:03.750+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:45:03.773+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:45:03.772+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:45:03.776+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:45:03.800+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:45:03.800+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:45:03.832+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:45:03.832+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:45:03.843+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.101 seconds
[2025-06-09T08:45:34.114+0000] {processor.py:157} INFO - Started process (PID=66) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:45:34.117+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:45:34.119+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:45:34.118+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:45:34.144+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:45:34.142+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:45:34.149+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:45:34.177+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:45:34.176+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:45:34.206+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:45:34.205+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:45:34.217+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.110 seconds
[2025-06-09T08:46:04.418+0000] {processor.py:157} INFO - Started process (PID=67) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:46:04.420+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:46:04.422+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:46:04.421+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:46:04.448+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:46:04.447+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:46:04.453+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:46:04.483+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:46:04.483+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:46:04.499+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:46:04.499+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:46:04.515+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.104 seconds
[2025-06-09T08:46:34.830+0000] {processor.py:157} INFO - Started process (PID=68) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:46:34.833+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:46:34.834+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:46:34.834+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:46:34.861+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:46:34.859+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:46:34.865+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:46:34.910+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:46:34.910+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:46:34.927+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:46:34.927+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:46:34.938+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.116 seconds
[2025-06-09T08:47:05.174+0000] {processor.py:157} INFO - Started process (PID=69) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:47:05.177+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:47:05.179+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:47:05.178+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:47:05.204+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:47:05.203+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:47:05.209+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:47:05.237+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:47:05.236+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:47:05.255+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:47:05.255+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:47:05.266+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.099 seconds
[2025-06-09T08:47:35.455+0000] {processor.py:157} INFO - Started process (PID=70) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:47:35.457+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:47:35.457+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:47:35.457+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:47:35.473+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:47:35.472+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:47:35.476+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:47:35.498+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:47:35.498+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:47:35.513+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:47:35.513+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:47:35.523+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.073 seconds
[2025-06-09T08:48:05.827+0000] {processor.py:157} INFO - Started process (PID=71) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:48:05.832+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:48:05.833+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:48:05.833+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:48:05.860+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:48:05.859+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:48:05.865+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:48:05.893+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:48:05.893+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:48:05.909+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:48:05.909+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:48:05.920+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.098 seconds
[2025-06-09T08:48:36.080+0000] {processor.py:157} INFO - Started process (PID=72) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:48:36.081+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:48:36.083+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:48:36.082+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:48:36.104+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:48:36.103+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:48:36.107+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:48:36.134+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:48:36.134+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:48:36.149+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:48:36.149+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:48:36.159+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.084 seconds
[2025-06-09T08:49:06.440+0000] {processor.py:157} INFO - Started process (PID=73) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:49:06.443+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:49:06.445+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:49:06.444+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:49:06.471+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:49:06.470+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:49:06.475+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:49:06.526+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:49:06.526+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:49:06.545+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:49:06.545+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:49:06.557+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.123 seconds
[2025-06-09T08:49:36.728+0000] {processor.py:157} INFO - Started process (PID=74) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:49:36.730+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:49:36.732+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:49:36.731+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:49:36.759+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:49:36.758+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:49:36.763+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:49:36.791+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:49:36.791+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:49:36.808+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:49:36.808+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:49:36.820+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.100 seconds
[2025-06-09T08:50:07.038+0000] {processor.py:157} INFO - Started process (PID=75) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:50:07.040+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:50:07.041+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:50:07.041+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:50:07.070+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:50:07.068+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:50:07.074+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:50:07.098+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:50:07.098+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:50:07.113+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:50:07.113+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:50:07.123+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.093 seconds
[2025-06-09T08:50:37.387+0000] {processor.py:157} INFO - Started process (PID=76) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:50:37.388+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:50:37.388+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:50:37.388+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:50:37.397+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:50:37.397+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:50:37.400+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:50:37.419+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:50:37.419+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:50:37.435+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:50:37.435+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:50:37.446+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.062 seconds
[2025-06-09T08:51:07.709+0000] {processor.py:157} INFO - Started process (PID=77) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:51:07.711+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:51:07.713+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:51:07.712+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:51:07.738+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:51:07.737+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:51:07.742+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:51:07.768+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:51:07.768+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:51:07.784+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:51:07.784+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:51:07.794+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.092 seconds
[2025-06-09T08:51:38.066+0000] {processor.py:157} INFO - Started process (PID=78) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:51:38.069+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:51:38.071+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:51:38.070+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:51:38.125+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:51:38.123+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:51:38.129+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:51:38.157+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:51:38.157+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:51:38.173+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:51:38.173+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:51:38.184+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.125 seconds
[2025-06-09T08:52:08.417+0000] {processor.py:157} INFO - Started process (PID=79) to work on /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:52:08.419+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/online_retail_etl.py for tasks to queue
[2025-06-09T08:52:08.421+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:52:08.420+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:52:08.453+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:52:08.449+0000] {templater.py:77} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 75, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/migrations/001_initial_schema.sql
[2025-06-09T08:52:08.464+0000] {processor.py:836} INFO - DAG(s) dict_keys(['online_retail_etl']) retrieved from /opt/airflow/dags/online_retail_etl.py
[2025-06-09T08:52:08.501+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:52:08.501+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2025-06-09T08:52:08.517+0000] {logging_mixin.py:150} INFO - [2025-06-09T08:52:08.517+0000] {dag.py:3508} INFO - Setting next_dagrun for online_retail_etl to 2025-06-08T00:00:00+00:00, run_after=2025-06-09T00:00:00+00:00
[2025-06-09T08:52:08.529+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/online_retail_etl.py took 0.120 seconds
